### ISSUE TITLE
Implement Decimal.toString()

### ISSUE THREAD

**Issue by darkfadr** [fiustars/binconv#8]

**Comment by gioperalto** [comment]
Hurry up Carlos!

We waiting on you!

**Comment by darkfadr** [comment]
@gioperalto Is this issue still open & Is Carlos even responding? If so, @cdebasa can you please give a status update. Otherwise, lets assign this task to someone

**Comment by gioperalto** [comment]
I did it, that's why I closed it. I wanted to move to phase 2. Phase 2 is
prepped.

Gio Peralto-Pritchard
Microsoft Student Partner for FIU
STARS http://stars.cs.fiu.edu - President, Tutor

**Comment by cdebasa** [comment]
My apologies for not delivering.

**Comment by darkfadr** [comment]
@cdebasa if you're not going to work on the task, do not pick it up. That will freeze up the development process.
